@startuml
class ECommerce {
    String nama
    String alamatUtama
    String owner
    DeliveryAPI deliveryType
    delivery(DeliveryAPI deliveryType)
}

interface DeliveryAPI {
    tarifPengiriman(Double jarak, Double berat)
    requestPengiriman(String asal, String tujuan)
}

class JNE {
    String nama
    String idEkspedisi
    String owner
    tarifPengiriman(Double jarak, Double berat)
    requestPengiriman(String asal, String tujuan)
}

class SiCepat {
    String nama
    String idEkspedisi
    String owner
    tarifPengiriman(Double jarak, Double berat)
    requestPengiriman(String asal, String tujuan)
}

ECommerce --> DeliveryAPI
DeliveryAPI <|-- JNE
DeliveryAPI <|-- SiCepat
@enduml

